version: "3.8"
services:
  neo4j:
    image: neo4j:2025.07.1
    container_name: neo4j-2025
    restart: unless-stopped
    ports: ["7474:7474", "7687:7687"]
    environment:
      NEO4J_AUTH: neo4j/test1234
      NEO4J_PLUGINS: '["apoc","gds","genai"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*,genai.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*,genai.*"
      NEO4J_db_checkpoint_throughput_limit: "256 MiB"
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 4G
      NEO4J_server_memory_pagecache_size: 2G
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ../db/import:/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/var/lib/neo4j/conf
    networks: [graphnet]
networks:
  graphnet: {}


